#NumberGuess CPU Player Program


FROM		java:8-jdk
RUN			mkdir /numberguesscpuplayer
WORKDIR		/numberguesscpuplayer
ADD			. /numberguesscpuplayer

ENTRYPOINT	["java","-jar", "/numberguesscpuplayer/target/NumberGuessCpuPlayer-0.0.1-SNAPSHOT.jar"]